import {createDriver} from '../../core/setup'
import * as data from './data'

const waitingTime = 30000
const searchTerm = data.generateTerm()

class RamdomRunner {
  async run(server, onlineDevice) {
    let driver = await createDriver(server, onlineDevice)
    const id = Math.floor(Math.random() * 10)
    const runFunc = this[`_run${id}`]
    await runFunc((driver))
  }

  async _run1(driver) {
    await driver
      .get('http://demoqa.com/contact/')
      .waitForElementByName('your-name', waitingTime)
      .click()
      .waitForElementByName('your-name', waitingTime)
      .clear()
      .waitForElementByName('your-name', waitingTime)
      .sendKeys(searchTerm)
      .waitForElementByName('your-email', waitingTime)
      .click()
      .waitForElementByName('your-email', waitingTime)
      .clear()
      .waitForElementByName('your-email', waitingTime)
      .sendKeys(searchTerm)
      .waitForElementByName('your-subject', waitingTime)
      .click()
      .waitForElementByName('your-subject', waitingTime)
      .clear()
      .waitForElementByName('your-subject', waitingTime)
      .sendKeys(searchTerm)
      .waitForElementByName('your-message', waitingTime)
      .click()
      .waitForElementByName('your-message', waitingTime)
      .clear()
      .waitForElementByName('your-message', waitingTime)
      .sendKeys(searchTerm)
      .quit()
  }

  async _run2(driver) {
    await driver
      .get('http://givetour.com/Account/Login')
      .waitForElementById('signin_email')
      .click()
      .waitForElementById('signin_email')
      .clear()
      .waitForElementById('signin_email')
      .sendKeys(searchTerm)
      .waitForElementById('signin_password')
      .click()
      .waitForElementById('signin_password')
      .clear()
      .waitForElementById('signin_password')
      .sendKeys(searchTerm)
      .waitForElementById('remember_me2')
      .click()
      .quit()
  }

  async _run3(driver) {
    await driver
      .get('http://givetour.com/Account/Register')
      .waitForElementById('UserName')
      .click()
      .waitForElementById('UserName')
      .clear()
      .waitForElementById('UserName')
      .sendKeys(searchTerm)
      .waitForElementById('user_password')
      .click()
      .waitForElementById('user_password')
      .clear()
      .waitForElementById('user_password')
      .sendKeys(searchTerm)
      .waitForElementById('user_password')
      .quit()
  }

  async _run4(driver) {
    await driver
      .get('https://tempail.com/en/temp-email/')
      .waitForElementByXPath('//div[@class="menu-dikey"]/a[@class="kopyala-link"]/em')
      .click()
      .waitForElementByXPath('//div[@class="menu-dikey"]/a[@class="yenile-link"]/em')
      .click()
      .waitForElementByXPath('//div[@class="menu-dikey"]/a[@class="kare-link"]/em')
      .click()
      .waitForElementByXPath('//div[@class="menu-dikey"]/a[@class="yoket-link"]/em')
      .click()
      .quit()
  }

  async _run5(driver) {
    await driver
      .get('http://newtours.demoaut.com/mercuryregister.php')
      .waitForElementByName('address1')
      .click()
      .waitForElementByName('address1')
      .clear()
      .waitForElementByName('address1')
      .sendKeys(searchTerm)
      .quit()
  }

  async _run6(driver) {
    await driver
      .get('https://www.mailinator.com/login.jsp')
      .waitForElementById('loginEmail')
      .click()
      .waitForElementById('loginEmail')
      .clear()
      .waitForElementById('loginEmail')
      .sendKeys(searchTerm)
      .waitForElementById('loginPassword')
      .click()
      .waitForElementById('loginPassword')
      .clear()
      .waitForElementById('loginPassword')
      .sendKeys(searchTerm)
      .waitForElementByXPath('//button[text()="Login"]')
      .click()
      .get('https://www.mailinator.com/forgotpass.jsp')
      .waitForElementById('forgotEmail')
      .click()
      .waitForElementById('forgotEmail')
      .clear()
      .waitForElementById('forgotEmail')
      .sendKeys(searchTerm)
      .waitForElementByXPath('//button[text()="Send Reset Email"]')
      .click()
      .quit()
  }

  async _run7(driver) {
    await driver
      .get('https://www.mailinator.com/signup.jsp')
      .waitForElementById('signupEmail')
      .click()
      .waitForElementById('signupEmail')
      .clear()
      .waitForElementById('signupEmail')
      .sendKeys(searchTerm)
      .waitForElementById('signupPassword')
      .click()
      .waitForElementById('signupPassword')
      .clear()
      .waitForElementById('signupPassword')
      .sendKeys(searchTerm)
      .waitForElementById('signupReenter')
      .click()
      .waitForElementById('signupReenter')
      .clear()
      .waitForElementById('signupReenter')
      .sendKeys(searchTerm)
      .waitForElementByXPath('//button[text()="Sign Up"]')
      .click()
      .quit()
  }

  async _run8(driver) {
    await driver
      .get('http://passwordsgenerator.net/')
      .waitForElementById('Symbols')
      .click()
      .waitForElementById('Numbers')
      .click()
      .waitForElementById('Lowercase')
      .click()
      .waitForElementById('Uppercase')
      .click()
      .waitForElementById('Uppercase')
      .click()
      .waitForElementById('NoAmb')
      .click()
      .waitForElementById('Client')
      .click()
      .waitForElementById('AutoSelect')
      .click()
      .waitForElementById('SaveSettings')
      .click()
      .waitForElementById('genbtn')
      .click()
      .waitForElementById('final_pass')
      .click()
      .waitForElementById('final_pass')
      .clear()
      .waitForElementById('final_pass')
      .sendKeys(searchTerm)
      .quit()
  }

  async _run9(driver) {
    await driver
      .get('http://store.demoqa.com/products-page/your-account/')
      .waitForElementByXPath('//input[@id="log"]')
      .click()
      .waitForElementByXPath('//input[@id="log"]')
      .clear()
      .waitForElementByXPath('//input[@id="log"]')
      .sendKeys(searchTerm)
      .waitForElementByXPath('//input[@id="pwd"]')
      .click()
      .waitForElementByXPath('//input[@id="pwd"]')
      .clear()
      .waitForElementByXPath('//input[@id="pwd"]')
      .sendKeys(searchTerm)
      .waitForElementById('rememberme')
      .click()
      .waitForElementById('login')
      .click()
      .quit()
  }

  async _run10(driver) {
    await driver
      .get('http://newtours.demoaut.com/mercurysignon.php')
      .waitForElementByName('userName')
      .click()
      .waitForElementByName('userName')
      .clear()
      .waitForElementByName('userName')
      .sendKeys(searchTerm)
      .waitForElementByName('password')
      .click()
      .waitForElementByName('password')
      .clear()
      .waitForElementByName('password')
      .sendKeys(searchTerm)
      .waitForElementByName('login')
      .click()
      .get('http://newtours.demoaut.com/mercuryregister.php')
      .waitForElementByName('firstName')
      .click()
      .waitForElementByName('firstName')
      .clear()
      .waitForElementByName('firstName')
      .sendKeys(searchTerm)
      .waitForElementByName('lastName')
      .click()
      .waitForElementByName('lastName')
      .clear()
      .waitForElementByName('lastName')
      .sendKeys(searchTerm)
      .waitForElementByName('phone')
      .click()
      .waitForElementByName('phone')
      .clear()
      .waitForElementByName('phone')
      .sendKeys(searchTerm)
      .waitForElementByName('userName')
      .click()
      .waitForElementByName('userName')
      .clear()
      .waitForElementByName('userName')
      .sendKeys(searchTerm)
      .quit()
  }
}

export default new RamdomRunner()
