<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>KrytonTestSuite GoogleNexus7</name>
   <isRerun>false</isRerun>
   <lastRun>2015-12-05T16:53:40</lastRun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <testSuiteGuid>05af0449-a418-4060-a898-69ea36fd087f</testSuiteGuid>
   <testCaseLink>
      <guid>ec726621-ae4d-4880-b55f-4244a04c6fab</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Verify_Compose_Email</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>SCRIPT</type>
         <value></value>
         <variableId>ed6098e5-5dbe-4d6b-bd1d-f68550df39de</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>SCRIPT</type>
         <value></value>
         <variableId>00af6c17-405d-4557-8650-ca1cc7c28f89</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>SCRIPT</type>
         <value></value>
         <variableId>29c37a4f-fed4-4fc0-b37f-2987b4e41c94</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>7364738e-b05e-4d97-adba-e8479768149c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Verify_Reply_Email</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>SCRIPT</type>
         <value></value>
         <variableId>8dc967e2-1159-4a65-87a1-c0eed183ac52</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>SCRIPT</type>
         <value></value>
         <variableId>3a62fd09-f093-4ecc-be3a-a0a1d3baa800</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>SCRIPT</type>
         <value></value>
         <variableId>8d850a17-724f-498e-98aa-7f0b301f4214</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
