source 'https://rubygems.org'

gem 'test-unit'
gem 'appium_lib'
gem 'watir-webdriver'
gem 'selenium-webdriver'
gem 'appium_flutter_finder', '~> 0.1.1'
gem 'appium_lib_core', '~> 3.3'
gem 'minitest', '~> 5.0'

